# Description: This file contains the secret configuration for the MongoDB database
# For best practices, it is recommended to store the secrets in a secure way like HashiCorp Vault
apiVersion: v1
kind: Secret
metadata:
  name: database-secret
type: Opaque
stringData:
  username: $(MONGODB_USERNAME)
  password: $(MONGODB_PASSWORD)
  replicaset: $(MONGODB_REPLICASET)
  address: $(MONGODB_ADDRESS)
  # address format: host1:27017,host2:27017,host3:27017