apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- database-secret.yaml
- cronjob.yaml

commonLabels:
  name: mongodb-compact

images:
- name: mehmetsever/mongodb-compact
  newTag: 1.0.0
