name: Docker Image CI

on:
  release:
    types: [published]

jobs:

  push_to_dockerhub:
    runs-on: ubuntu-latest
    permissions:
        packages: write
        contents: read
        attestations: write
        id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5.5.1
      with:
        images: mehmetsever/mongodb-compact

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v5.4.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        